-- 支付类二维码表
CREATE TABLE TBL_PAYMENT_QRCODE(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);



-- 支付类二维码历史表
CREATE TABLE TBL_PAYMENT_QRCODE_HIS(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);


-- 识别类二维码表
CREATE TABLE TBL_IDENTITY_QRCODE(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 识别类二维码历史表
CREATE TABLE TBL_IDENTITY_QRCODE_HIS(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 运营类二维码表
CREATE TABLE TBL_OPERATION_QRCODE(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 运营类二维码历史表
CREATE TABLE TBL_OPERATION_QRCODE_HIS(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);


-- 排队类二维码表
CREATE TABLE TBL_QUEUE_QRCODE(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 排队类二维码历史表
CREATE TABLE TBL_QUEUE_QRCODE_HIS(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 展示类二维码表
CREATE TABLE TBL_DISPLAY_QRCODE(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 展示类二维码历史表
CREATE TABLE TBL_DISPLAY_QRCODE_HIS(
  QRCODE_ID VARCHAR(40) primary key NOT NULL,
  TEMPLET_ID VARCHAR(32),
  CUSTOM_MOD_DATE VARCHAR(8),
  CUSTOM_MOD_TIME VARCHAR(6),
  EXPIRY_DATE_TIME VARCHAR(14),
  PICTURE_ID VARCHAR(32),
  EXPIRY_STATUS VARCHAR(2),
  BEFORE_TOKEN VARCHAR(40),
  TOKEN VARCHAR(40),
  ORG_ID VARCHAR(12),
  QR_URL VARCHAR(40),
  DATA DBCLOB,
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);


-- 二维码交易流水表
CREATE TABLE TBL_QRCODE_TXN(
  TXN_ID VARCHAR(32) primary key not null,
  ORG_TXN_ID VARCHAR(32),
  QRCODE_ID VARCHAR(40),
  CHANNEL_ID VARCHAR(32),
  CHANNEL_NO VARCHAR(32),
  CHANNEL_DATE VARCHAR(8),
  CHANNEL_TIME VARCHAR(6),
  RECEIVE_DATE VARCHAR(8),
  RECEIVE_TIME VARCHAR(6),
  REQ_SYS_NO VARCHAR(6),
  RESP_SYS_NO VARCHAR(6),
  APPLICATION VARCHAR(6),
  PURPOSE VARCHAR(6),
  SCENE VARCHAR(6),
  REQUEST_DATA DBCLOB,
  TRANS_TYPE VARCHAR(6),
  STATUS VARCHAR(2),
  REMARK VARCHAR(200),
  RETURN_CODE VARCHAR(8),
  RETURN_DESC VARCHAR(200),
  RETURN_DATE VARCHAR(8),
  RETURN_TIME VARCHAR(6),
  ORG_ID VARCHAR(12),
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);

-- 二维码交易流水历史表
CREATE TABLE TBL_QRCODE_TXN_HIS(
  TXN_ID VARCHAR(32) primary key not null,
  ORG_TXN_ID VARCHAR(32),
  QRCODE_ID VARCHAR(40),
  CHANNEL_ID VARCHAR(32),
  CHANNEL_NO VARCHAR(32),
  CHANNEL_DATE VARCHAR(8),
  CHANNEL_TIME VARCHAR(6),
  RECEIVE_DATE VARCHAR(8),
  RECEIVE_TIME VARCHAR(6),
  REQ_SYS_NO VARCHAR(6),
  RESP_SYS_NO VARCHAR(6),
  APPLICATION VARCHAR(6),
  PURPOSE VARCHAR(6),
  SCENE VARCHAR(6),
  REQUEST_DATA DBCLOB,
  TRANS_TYPE VARCHAR(6),
  STATUS VARCHAR(2),
  REMARK VARCHAR(200),
  RETURN_CODE VARCHAR(8),
  RETURN_DESC VARCHAR(200),
  RETURN_DATE VARCHAR(8),
  RETURN_TIME VARCHAR(6),
  ORG_ID VARCHAR(12),
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);


-- 密钥管理表
CREATE TABLE TBL_KEY_LIST(
  ID VARCHAR(100) primary key not null,
  KEYT_METHOD VARCHAR(14),
  VERSION VARCHAR(14),
  KEYT VARCHAR(100),
  IS_IN_USE VARCHAR(2),
  ORG_ID VARCHAR(12),
  CRT_USER VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE VARCHAR(8),
  CRT_TIME VARCHAR(6),
  UPD_DATE VARCHAR(2),
  MISC1 VARCHAR(32),
  MISC2 VARCHAR(32),
  MISC3 VARCHAR(32),
  MISC4 VARCHAR(32)
);


-- 系统操作日志表
CREATE TABLE SYS_FHLOG
(
  FHLOG_ID VARCHAR(100) NOT NULL,
  USERNAME VARCHAR(100),
  CZTIME   VARCHAR(32),
  CONTENT  VARCHAR(255),
  PRIMARY KEY (FHLOG_ID)
);

-- 系统在线用户表
CREATE TABLE SYS_LOGIN_USER (
  USER_ID    VARCHAR(100) NOT NULL,
  LOGIN_TS   VARCHAR(14),
  END_TS     VARCHAR(14),
  SESSION_ID VARCHAR(100),
  PRIMARY KEY (USER_ID)
);

CREATE TABLE SYS_MENU (
  MENU_ID    INTEGER NOT NULL,
  MENU_NAME  VARCHAR(255),
  MENU_URL   VARCHAR(255),
  PARENT_ID  VARCHAR(100),
  MENU_ORDER VARCHAR(100),
  MENU_ICON  VARCHAR(60),
  MENU_TYPE  VARCHAR(10),
  MENU_STATE INTEGER,
  PRIMARY KEY (MENU_ID)
);


-- 系统角色表
CREATE TABLE SYS_ROLE (
  ROLE_ID     VARCHAR(100) NOT NULL,
  ROLE_NAME   VARCHAR(100),
  RIGHTS      VARCHAR(255),
  PARENT_ID   VARCHAR(100),
  ADD_QX      VARCHAR(255),
  DEL_QX      VARCHAR(255),
  EDIT_QX     VARCHAR(255),
  CHA_QX      VARCHAR(255),
  ROLE_STATUS CHARACTER(1),
  PRIMARY KEY (ROLE_ID)
);


-- 系统用户表
CREATE TABLE SYS_USER (
  USER_ID      VARCHAR(100) NOT NULL,
  USERNAME     VARCHAR(255),
  PASSWORD     VARCHAR(255),
  NAME         VARCHAR(255),
  RIGHTS       VARCHAR(255),
  ROLE_ID      VARCHAR(100),
  LAST_LOGIN   VARCHAR(255),
  IP           VARCHAR(100),
  STATUS       VARCHAR(32),
  BZ           VARCHAR(255),
  SKIN         VARCHAR(100),
  EMAIL        VARCHAR(32),
  NUMBER       VARCHAR(100),
  PHONE        VARCHAR(32),
  BRH_ID       VARCHAR(10),
  GENDER       VARCHAR(1),
  REGISTER_DT  VARCHAR(8),
  PWD_OUT_DATE VARCHAR(8),
  OPR_STA      VARCHAR(1),
  PRIMARY KEY (USER_ID)
);


-- 黑名单表
CREATE TABLE TBL_BLACK_LIST (
  BLANK_ID    VARCHAR(32) NOT NULL,
  BLANK_TYPE  VARCHAR(4),
  BLANK_NO    VARCHAR(32),
  BLANK_DESC  VARCHAR(200),
  IS_USE      VARCHAR(1),
  EXPIRY_TIME VARCHAR(14),
  CRT_USER    VARCHAR(12),
  CRT_TIME    VARCHAR(14),
  UPDATE_USER VARCHAR(12),
  UPDATE_TIME VARCHAR(14),
  MISC1       VARCHAR(32),
  MISC2       VARCHAR(32),
  MISC3       VARCHAR(64),
  MISC4       VARCHAR(64),
  CONSTRAINT PK_TBL_BLACK_LIST PRIMARY KEY (BLANK_ID)
);

-- 机构信息表
CREATE TABLE TBL_BRH_INFO (
  BRH_ID          VARCHAR(10)  NOT NULL,
  CUP_BRH_ID      VARCHAR(128) NOT NULL,
  BRH_LEVEL       VARCHAR(1)   NOT NULL,
  BRH_STA         VARCHAR(1)   NOT NULL,
  UP_BRH_ID       VARCHAR(15)  NOT NULL,
  REG_DT          VARCHAR(8)   NOT NULL,
  POST_CD         VARCHAR(6)   NOT NULL,
  BRH_ADDR        VARCHAR(120) NOT NULL,
  BRH_NAME        VARCHAR(120) NOT NULL,
  BRH_TEL_NO      VARCHAR(30)  NOT NULL,
  BRH_CONT_NAME   VARCHAR(60),
  RESV1           VARCHAR(190),
  RESV2           VARCHAR(190),
  LAST_UPD_OPR_ID VARCHAR(40),
  LAST_UPD_TXN_ID VARCHAR(10),
  LAST_UPD_TS     VARCHAR(14),
  BANK_FLAG       VARCHAR(3),
  CORE_BRH_ID     VARCHAR(6),
  CONSTRAINT UNI_TBL_BRH_INFO PRIMARY KEY (BRH_ID)
);

-- 批量任务记录
CREATE TABLE TBL_JOB_PROCE (
  PK_JOB_PROCE VARCHAR(32) NOT NULL,
  TASK_ID      VARCHAR(6),
  TASK_DATE    VARCHAR(8),
  START_DATE   VARCHAR(8),
  STAR_TIME    VARCHAR(6),
  END_DATE     VARCHAR(8),
  END_TIME     VARCHAR(6),
  JOB_TYPE     VARCHAR(2),
  JOB_STATUS   VARCHAR(2),
  REMARK       VARCHAR(256),
  CRT_USER     VARCHAR(12),
  CRT_TIME     VARCHAR(14),
  UPDATE_USER  VARCHAR(12),
  UPDATE_TIME  VARCHAR(14),
  MISC1        VARCHAR(32),
  MISC2        VARCHAR(32),
  MISC3        VARCHAR(64),
  MISC4        VARCHAR(64),
  TASK_NAME    VARCHAR(64),
  CONSTRAINT PK_TBL_JOB_PROCE PRIMARY KEY (PK_JOB_PROCE)
);

CREATE INDEX TASK_ID ON TBL_JOB_PROCE (TASK_ID);


-- 二维码模块表
CREATE TABLE TBL_QR_MODULE (
  QR_MOD_ID        VARCHAR(32) NOT NULL,
  QR_MOD_CODE      VARCHAR(32),
  QR_MOD_NAME      VARCHAR(32),
  QRCODE_VERSION   VARCHAR(1),
  ENCODE_MODE      VARCHAR(1),
  GENERATION_MODE  VARCHAR(1),
  EXPIRY_TYPE      VARCHAR(1),
  EXPIRY_DATE      VARCHAR(2),
  ACTION_SCOPE     VARCHAR(1),
  READ_MODE        VARCHAR(1),
  RISK_LEVEL       VARCHAR(1),
  BACK_CODE        VARCHAR(1),
  ENTRY_FLAG       VARCHAR(1),
  KEY_VERSION      VARCHAR(1),
  REQ_SYS          VARCHAR(4),
  INDUSTRY_APP     VARCHAR(3),
  USE_TYPE         VARCHAR(1),
  USE_SCENE        VARCHAR(2),
  CUS_MOD_STATUS   VARCHAR(2),
  ORG_ID           VARCHAR(12),
  QR_URL           VARCHAR(40),
  LAST_UPD_OPER_ID VARCHAR(32),
  LAST_UPD_TIME    VARCHAR(14),
  CRT_OPER_ID      VARCHAR(32),
  CREATE_TIME      VARCHAR(14),
  MISC1            VARCHAR(32),
  MISC2            VARCHAR(32),
  MISC3            VARCHAR(32),
  MISC4            VARCHAR(32),
  CONSTRAINT PK_TBL_QR_MODULE PRIMARY KEY (QR_MOD_ID)
);

-- 二维码模版参数定义
CREATE TABLE TBL_QR_PARAM (
  ID          VARCHAR(32) NOT NULL,
  PARAM_CODE  VARCHAR(4),
  PARAM_NAME  VARCHAR(200),
  PROP_CODE   VARCHAR(4),
  PROP_NAME   VARCHAR(200),
  PARAM_DESC  VARCHAR(400),
  FLAG_ENABLE VARCHAR(2),
  CRT_USER    VARCHAR(12),
  CRT_DATE    VARCHAR(8),
  CRT_TIME    VARCHAR(6),
  UPDATE_USER VARCHAR(12),
  UPDATE_DATE VARCHAR(8),
  UPDATE_TIME VARCHAR(6),
  CONSTRAINT PK_TBL_QR_PARAM PRIMARY KEY (ID)
);

-- 系统参数表
CREATE TABLE TBL_SYS_PARAM (
  PARAM_ID    VARCHAR(32) NOT NULL,
  PARAM_CODE  VARCHAR(32),
  PARAM_DESC  VARCHAR(100),
  PARAM_VALUE VARCHAR(512),
  TYPE_CODE   VARCHAR(32),
  TYPE_NAME   VARCHAR(60),
  VALID_FLAG  VARCHAR(2),
  SORT_ORDER  VARCHAR(11),
  ORG_ID      VARCHAR(12),
  CRT_USER    VARCHAR(12),
  UPDATE_USER VARCHAR(12),
  CRT_DATE    VARCHAR(8),
  CRT_TIME    VARCHAR(6),
  UPD_DATE    VARCHAR(6),
  UPD_TIME    VARCHAR(2),
  MISC1       VARCHAR(32),
  MISC2       VARCHAR(32),
  MISC3       VARCHAR(64),
  MISC4       VARCHAR(64),
  CONSTRAINT PK_TBL_SYS_PARAM PRIMARY KEY (PARAM_ID)
);


-- 任务轮询表
CREATE TABLE TBL_TASK_POLL_LIST (
  TASK_ID       VARCHAR(6) NOT NULL,
  TASK_NAME     VARCHAR(64),
  EXECUTE_TIME  VARCHAR(20),
  EXECUTE_CLASS VARCHAR(64),
  STATUS        VARCHAR(1),
  ORG_ID        VARCHAR(12),
  CRT_DATE      VARCHAR(8),
  CRT_TIME      VARCHAR(6),
  UPD_DATE      VARCHAR(6),
  UPD_TIME      VARCHAR(2),
  CRT_USER      VARCHAR(12),
  UPDATE_USER   VARCHAR(12),
  MISC1         VARCHAR(32),
  MISC2         VARCHAR(32),
  MISC3         VARCHAR(64),
  MISC4         VARCHAR(64),
  CONSTRAINT PK_TBL_TASK_POLL_LIST PRIMARY KEY (TASK_ID)
);



